In [19]:
import pandas as pd

In [20]:
p = pd.Series(['e',4,'$','_'])

In [21]:
pd.Series(dtype=p[0])

Series([], dtype: float16)

In [22]:
p[1].dtype

AttributeError: 'int' object has no attribute 'dtype'

In [23]:
import pandas
pandas.__version__

'1.4.2'

# PD. SERIES(DATA,INDEX,DTYPE)

In [24]:
import numpy as np

p = pd.Series([2,54,65,65,58,98,67],dtype='int32')

In [25]:
p

0     2
1    54
2    65
3    65
4    58
5    98
6    67
dtype: int32

In [26]:
p[3]=165

In [27]:
p

0      2
1     54
2     65
3    165
4     58
5     98
6     67
dtype: int32

In [28]:
p2 = pd.Series([2,54,65,65,58,98,67],index=list('abcdefg'),dtype='int32')

In [29]:
p2.ndim

1

In [30]:
p2.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')

In [31]:
p2.dtype

dtype('int32')

In [32]:
p2.size

7

In [33]:
p2.shape

(7,)

In [34]:
p2.values

array([ 2, 54, 65, 65, 58, 98, 67])

In [35]:
p2['a':'d']

a     2
b    54
c    65
d    65
dtype: int32

In [36]:
p3 = pd.Series([2,54,65,65,58,98,67],index=list('!@#$%^&'),dtype='int32')
p3

!     2
@    54
#    65
$    65
%    58
^    98
&    67
dtype: int32

In [37]:
p3

!     2
@    54
#    65
$    65
%    58
^    98
&    67
dtype: int32

In [38]:
p3['!':'%']

!     2
@    54
#    65
$    65
%    58
dtype: int32

In [39]:
p1 = pd.Series([25,255,64,98,57,64,69,19,25],index=range(101,92,-1))
p1

101     25
100    255
99      64
98      98
97      57
96      64
95      69
94      19
93      25
dtype: int64

In [40]:
p1[0:5]

101     25
100    255
99      64
98      98
97      57
dtype: int64

In [41]:
pd.Series([45,25,48,49,65,59,67,38,89],index=['a','b','c','d','e','r','t','f','l'])

a    45
b    25
c    48
d    49
e    65
r    59
t    67
f    38
l    89
dtype: int64

In [42]:
type(p3)

pandas.core.series.Series

# DATAFRAME

In [43]:
d = pd.DataFrame([12,'u','*',65])

In [44]:
type(d)

pandas.core.frame.DataFrame

In [45]:
d.index

RangeIndex(start=0, stop=4, step=1)

In [46]:
d.values

array([[12],
       ['u'],
       ['*'],
       [65]], dtype=object)

In [47]:
d.size

4

In [48]:
d.shape

(4, 1)

In [49]:
d.dtypes

0    object
dtype: object

# PD.DATAFRAME (DATA,INDEX,COLUMNS,DTYPES)

In [50]:
d = pd.DataFrame(['6',9,'j',78,98]
            )

In [51]:
d.values

array([['6'],
       [9],
       ['j'],
       [78],
       [98]], dtype=object)

In [52]:
d[0]+d[0]

0     66
1     18
2     jj
3    156
4    196
Name: 0, dtype: object

In [53]:
d1 = pd.DataFrame(['j','k','9','yy','l'])

In [54]:
d1[1]+d1[1]

KeyError: 1

In [55]:
d2=pd.DataFrame([[6,8.2,9,90,56],[98,9,4,3,'6']])

In [56]:
d2

0    1  2   3   4
0   6  8.2  9  90  56
1  98  9.0  4   3   6

In [57]:
d2[3]/d2[3]

0    1.0
1    1.0
Name: 3, dtype: float64

In [58]:
d2[4]+d2[4]

0    112
1     66
Name: 4, dtype: object

#### 

In [59]:
d2

0    1  2   3   4
0   6  8.2  9  90  56
1  98  9.0  4   3   6

In [60]:
d3=pd.DataFrame([6,8.2,9,90,56],[98,9,4,3,6])

In [61]:
d3

0
98   6.0
9    8.2
4    9.0
3   90.0
6   56.0

In [62]:
d3[0]*d3[0]

98      36.00
9       67.24
4       81.00
3     8100.00
6     3136.00
Name: 0, dtype: float64

In [63]:
d4 = pd.DataFrame([5.7,8,9,5,4],range(1,6),dtype='int')
d4

C:\Users\Rakesh\AppData\Local\Temp\ipykernel_2068\1177673535.py:1: FutureWarning: In a future version, passing float-dtype values and an integer dtype to DataFrame will retain floating dtype if they cannot be cast losslessly (matching Series behavior). To retain the old behavior, use DataFrame(data).astype(dtype)
  d4 = pd.DataFrame([5.7,8,9,5,4],range(1,6),dtype='int')


0
1  5
2  8
3  9
4  5
5  4

In [64]:
d4.astype('float')

0
1  5.0
2  8.0
3  9.0
4  5.0
5  4.0

In [65]:
dx = {'nam':('A','B','C'),'age':(24,29,35),'roll':(1,2,3)}

In [66]:
pd.DataFrame(dx)

nam  age  roll
0   A   24     1
1   B   29     2
2   C   35     3

In [67]:
dy = {5,6,77}

In [68]:
pd.DataFrame(dx,dy,columns=('val1','val2','val3'))

val1 val2 val3
5   NaN  NaN  NaN
77  NaN  NaN  NaN
6   NaN  NaN  NaN

In [82]:
data = [pd.Series([2,3,4]),pd.Series([22,33,44]),pd.Series([222,333,444])]
data

[0    2
 1    3
 2    4
 dtype: int64,
 0    22
 1    33
 2    44
 dtype: int64,
 0    222
 1    333
 2    444
 dtype: int64]

In [85]:
e = pd.DataFrame(data,columns=(['val1','val2','val3']))

In [86]:
e

val1  val2  val3
0   NaN   NaN   NaN
1   NaN   NaN   NaN
2   NaN   NaN   NaN

In [72]:
e['val1']+e['val1']

0   NaN
1   NaN
2   NaN
Name: val1, dtype: float64

In [80]:
import numpy as np
n = np.random.random((4,4))
n

array([[0.9997157 , 0.70494031, 0.65801757, 0.76977467],
       [0.61658191, 0.44119266, 0.89667928, 0.48660894],
       [0.44291963, 0.85656496, 0.03899032, 0.01466239],
       [0.68904558, 0.47184155, 0.72471129, 0.84764012]])

In [81]:
pd.DataFrame(n,columns=['val1','val2','val3','val4'])

val1      val2      val3      val4
0  0.999716  0.704940  0.658018  0.769775
1  0.616582  0.441193  0.896679  0.486609
2  0.442920  0.856565  0.038990  0.014662
3  0.689046  0.471842  0.724711  0.847640

In [ ]:
pd.DataFrame