In [ ]:
import numpy as np 
np.array([1,2,3])


In [ ]:
np.__version__

# NUMPY VERSion


In [1]:
import numpy as np 
np.__version__

'1.21.5'

In [2]:
print('hello')

hello


In [3]:
a = np.array([1,2,3])

array([1, 2, 3])

In [8]:
b = [1,2,3]
b


[1, 2, 3]

In [10]:
a = np.array([1,2,3])
p = a*5


array([ 5, 10, 15])

In [16]:
c=b*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
print(a.__sizeof__())
print(c.__sizeof__())

NameError: name 'a' is not defined

In [2]:
print('hello')

hello


In [2]:
a = np.array([1,2,3])
a


NameError: name 'np' is not defined

In [3]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [4]:
x = 10
x

10

In [5]:
y = 88
y

88

In [6]:
print(dir())

['In', 'Out', '_', '_3', '_4', '_5', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_i2', '_i3', '_i4', '_i5', '_i6', '_ih', '_ii', '_iii', '_oh', 'exit', 'get_ipython', 'np', 'quit', 'x', 'y']


for i in range(6):
print(i)

In [10]:
for i in range(8):
    print(i, end=' ')

0 1 2 3 4 5 6 7 

In [12]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 '__peg_parser__',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [14]:
for i in range(9
              ):
    print(i*'*')


*
**
***
****
*****
******
*******
********


In [19]:
for i in range(9):
    print(chr(i+64)*i)
    


A
BB
CCC
DDDD
EEEEE
FFFFFF
GGGGGGG
HHHHHHHH


In [2]:
import numpy as np
x = np.array([10,20,30])

x.ndim

1

In [6]:
x = np.array([[[1,2],[4,6],[7,8],[90,9]],[[3,4],[41,6],[71,8],[90,91]],[[4,57],[4,62],[7,82],[90,92]]])
x

array([[[ 1,  2],
        [ 4,  6],
        [ 7,  8],
        [90,  9]],

       [[ 3,  4],
        [41,  6],
        [71,  8],
        [90, 91]],

       [[ 4, 57],
        [ 4, 62],
        [ 7, 82],
        [90, 92]]])

In [7]:
x.shape

(3, 4, 2)

In [11]:
x.ndim

3

In [14]:
x = np.array([[[1,2],[3,4],[4,5]]])
x

array([[[1, 2],
        [3, 4],
        [4, 5]]])

In [19]:
x.ndim

3

In [25]:
x = np.array([1,2,3,4, 6, 67,35, 67,1])
x

array([ 1,  2,  3,  4,  6, 67, 35, 67,  1])

In [26]:
x.ndim

1

In [28]:
x = set(x)
x

{1, 2, 3, 4, 6, 35, 67}

In [41]:
x = np.array([[1,2,3],[12,54,54],[3,4,5],[546,56,65]],[[4,5,6],[1,8,9]])
x

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [38]:
x.shape

(3, 2, 3)

In [3]:
import numpy as np
x = np.array([1,2,3,8,5,6])b
x

array([1, 2, 3, 8, 5, 6])

In [7]:
x = np.array([[1,2,3,6,8,99],[1,4,6,8,99,98]])
x

array([[ 1,  2,  3,  6,  8, 99],
       [ 1,  4,  6,  8, 99, 98]])

In [8]:
x.shape

(2, 6)

In [20]:
x = np.array([[[2,4],[6,8]],[[3,4],[12,45,]]])
x

array([[[ 2,  4],
        [ 6,  8]],

       [[ 3,  4],
        [12, 45]]])

In [21]:
x.shape

(2, 2, 2)

In [23]:
arr =  np.arange(10000000)
arr

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [24]:
p_list = range(10000000)
p_list

range(0, 10000000)

In [28]:
%%time 
for i in range(100):
    print(i,'=',i**3)
    

0 = 0
1 = 1
2 = 8
3 = 27
4 = 64
5 = 125
6 = 216
7 = 343
8 = 512
9 = 729
10 = 1000
11 = 1331
12 = 1728
13 = 2197
14 = 2744
15 = 3375
16 = 4096
17 = 4913
18 = 5832
19 = 6859
20 = 8000
21 = 9261
22 = 10648
23 = 12167
24 = 13824
25 = 15625
26 = 17576
27 = 19683
28 = 21952
29 = 24389
30 = 27000
31 = 29791
32 = 32768
33 = 35937
34 = 39304
35 = 42875
36 = 46656
37 = 50653
38 = 54872
39 = 59319
40 = 64000
41 = 68921
42 = 74088
43 = 79507
44 = 85184
45 = 91125
46 = 97336
47 = 103823
48 = 110592
49 = 117649
50 = 125000
51 = 132651
52 = 140608
53 = 148877
54 = 157464
55 = 166375
56 = 175616
57 = 185193
58 = 195112
59 = 205379
60 = 216000
61 = 226981
62 = 238328
63 = 250047
64 = 262144
65 = 274625
66 = 287496
67 = 300763
68 = 314432
69 = 328509
70 = 343000
71 = 357911
72 = 373248
73 = 389017
74 = 405224
75 = 421875
76 = 438976
77 = 456533
78 = 474552
79 = 493039
80 = 512000
81 = 531441
82 = 551368
83 = 571787
84 = 592704
85 = 614125
86 = 636056
87 = 658503
88 = 681472
89 = 704969
90 = 729000
91 = 

In [30]:
for i in arange(100):
    print(i,end = ' ')

NameError: name 'arange' is not defined

In [2]:
import numpy as np
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [4]:
np.zeros([3,43])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones([3,3,3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [32]:
np.zeros([1,1,1],dtype = int)

array([[[0]]])

In [29]:
np.zeros([1,1,2])

array([[[0., 0.]]])

In [30]:
np.zeros([1,1,3])

array([[[0., 0., 0.]]])

In [31]:
np.zeros([1,2,1])

array([[[0.],
        [0.]]])

In [6]:
np.ones([1,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
np.ones([1,2,2])

array([[[1., 1.],
        [1., 1.]]])

In [8]:
np.ones([1,3,2])

array([[[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [9]:
np.zeros([1,3,3
         ])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
np.zeros([2,1,1
         ])

array([[[0.]],

       [[0.]]])

In [11]:
np.zeros([2,1,2])

array([[[0., 0.]],

       [[0., 0.]]])

In [12]:
np.zeros([2,1,3])

array([[[0., 0., 0.]],

       [[0., 0., 0.]]])

In [13]:
np.zeros([2,2,1])

array([[[0.],
        [0.]],

       [[0.],
        [0.]]])

In [14]:
np.zeros([2,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [15]:
np.zeros([2,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
np.zeros([2,3,1])

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [17]:
np.zeros([2,3,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
np.zeros([2,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
np.zeros([3,1,1])

array([[[0.]],

       [[0.]],

       [[0.]]])

In [20]:
np.zeros([3,1,2])

array([[[0., 0.]],

       [[0., 0.]],

       [[0., 0.]]])

In [21]:
np.zeros([3,1,3])

array([[[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]]])

In [22]:
np.zeros([3,2,1])

array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]])

In [23]:
np.zeros([3,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [24]:
np.zeros([3,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
np.zeros([3,3,1])

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [26]:
np.zeros([3,3,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [27]:
np.zeros([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])