In [2]:
import numpy as np
a = np.array([[3,4,5],[3,6,8],[7,2,3]])

In [3]:
a%3==0

array([[ True, False, False],
       [ True,  True, False],
       [False, False,  True]])

In [5]:
b = np.arange(24)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
b.resize(4,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [15]:
b%3==0

array([[ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False]])

In [16]:
b[b%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [18]:
b%5==0

array([[ True, False, False, False, False,  True],
       [False, False, False, False,  True, False],
       [False, False, False,  True, False, False],
       [False, False,  True, False, False, False]])

In [19]:
b[b%5==0]

array([ 0,  5, 10, 15, 20])

In [20]:
b%4==0

array([[ True, False, False, False,  True, False],
       [False, False,  True, False, False, False],
       [ True, False, False, False,  True, False],
       [False, False,  True, False, False, False]])

In [21]:
b[b%4==0]

array([ 0,  4,  8, 12, 16, 20])

In [22]:
b%4==0,b%3==0

(array([[ True, False, False, False,  True, False],
        [False, False,  True, False, False, False],
        [ True, False, False, False,  True, False],
        [False, False,  True, False, False, False]]),
 array([[ True, False, False,  True, False, False],
        [ True, False, False,  True, False, False],
        [ True, False, False,  True, False, False],
        [ True, False, False,  True, False, False]]))

In [26]:
b[(b%4==0)|(b%3==0)]

array([ 0,  3,  4,  6,  8,  9, 12, 15, 16, 18, 20, 21])

In [29]:
a[a%3==0]

array([3, 3, 6, 3])

In [34]:
b[(b%3==0)|(b%4==0)|(b%5==0)]

array([ 0,  3,  4,  5,  6,  8,  9, 10, 12, 15, 16, 18, 20, 21])

# 4X4 array and set truue and false value 


In [8]:
import numpy as np
a = np.ones((4,4),dtype=bool)
a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [10]:
a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [11]:
~np.ones((4,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [12]:
np.full((4,4),fill_value=True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [13]:
np.full((4,4),fill_value=False)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [14]:
np.full((4,4),fill_value=1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [3]:
import numpy as np
np.ones((4,4),dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# Create a 4x4 array whose diagonal values set to True and Non diagonal False

In [3]:
import numpy as np
np.eye((6),dtype=bool)

array([[ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False,  True]])

# Create a 4x4 array whose diagonal values set to False and Non diagonal True

In [4]:
~np.eye((6),dtype=bool)

array([[False,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True],
       [ True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True, False]])

In [6]:
np.array([0,False,87,-98,65])

array([  0,   0,  87, -98,  65])

In [8]:
~np.array([0,False,87,-98,65],dtype=bool)

array([ True,  True, False, False, False])

In [11]:
a = np.arange(24)

In [16]:
a.resize((6,4))

In [ ]:
#printtt central 4 elements of a

In [22]:
a[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [25]:
a.shape

(6, 4)

In [31]:
a[::5,::3]

array([[ 0,  3],
       [20, 23]])

In [29]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
a[::5,::3]

array([[ 0,  3],
       [20, 23]])

In [32]:
a[1:5:3,0:4:3]

array([[ 4,  7],
       [16, 19]])

In [37]:
a[1:-1:3,1:3]

array([[5, 6]])

In [38]:
a[2,2]

10

In [39]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
a[3::4,1:3]

array([[13, 14]])

In [41]:
a[4]

array([16, 17, 18, 19])

In [42]:
a[-1::-1]

array([[20, 21, 22, 23],
       [16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [43]:
a[::1,3:4:1]

array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])

In [46]:
a[:,-2]

array([ 2,  6, 10, 14, 18, 22])

In [47]:
a[2,:]

array([ 8,  9, 10, 11])

In [48]:
a[:,-2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [50]:
a[1:5,2:6]

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [52]:
a[1:5,2:6] = [[0,0],[1,1],[2,2],[3,3]]

In [53]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  0,  0],
       [ 8,  9,  1,  1],
       [12, 13,  2,  2],
       [16, 17,  3,  3],
       [20, 21, 22, 23]])

In [56]:
a[0,2]= 9
a

array([[ 0,  1,  9,  3],
       [ 4,  5,  9,  0],
       [ 8,  9,  1,  1],
       [12, 13,  2,  2],
       [16, 17,  3,  3],
       [20, 21, 22, 23]])