In [1]:
import numpy as np

# SHAPE MANIPULATION

In [2]:
a = np.arange(48)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

#RESHAPE

In [4]:
a.reshape(6,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [5]:
a.reshape(2,4,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [6]:
a.reshape(4,2,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [7]:
a.reshape(4,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

# RESIZE

######GIVES INPLACE variable

In [9]:
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [11]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [10]:
a.resize(4,12)

In [12]:
a.resize(2,24)

In [13]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
        40, 41, 42, 43, 44, 45, 46, 47]])

In [16]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [15]:
a.resize(3,4,4)

In [17]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

# SHAPE

In [18]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [20]:
a.reshape(3,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [19]:
a.shape

(3, 4, 4)

In [22]:
a.shape = 6,2,4

In [23]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [24]:
a.shape

(6, 2, 4)

In [28]:
a.reshape(2,6,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [29]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [30]:
a.reshape(48)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [36]:
y = a.reshape(2,24)

In [35]:
x = a.reshape(48)

In [33]:
a.shape

(6, 2, 4)

In [37]:
x.shape

(48,)

In [38]:
y.shape

(2, 24)

In [39]:
a.resize(48)

In [40]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [41]:
a.shape

(48,)

In [42]:
a.resize(6,8)

In [43]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [44]:
a.shape

(6, 8)

In [45]:
a.resize(3,4,4)

In [46]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [47]:
a.shape

(3, 4, 4)

# RAVEL AND FLATTEN

In [48]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [50]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [51]:
a[0]=100

In [52]:
a


array([[[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]],

       [[ 32,  33,  34,  35],
        [ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]]])

In [53]:
a.flatten()

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47])

In [55]:
a[0]=0
a

array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [60]:
b = a.ravel()
b

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [63]:
b[0] = 100
b

array([100,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47])

In [64]:
a

array([[[100,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]],

       [[ 32,  33,  34,  35],
        [ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]]])

In [66]:
c = a.flatten()
c

array([100,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47])

In [68]:
c[0] = 200
c

array([200,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47])

In [69]:
a

array([[[100,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]],

       [[ 32,  33,  34,  35],
        [ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]]])

Above shows RAVEL IS VIEW (DEEP COPY) AND FLATTEN IS COPY (SHALLOW COPY)

In [74]:
print(id(a))
print(id(c))
print(id(b))

2677271632080
2677315793136
2677315660944


# TRANSPOSE

In [75]:
a

array([[[100,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]],

       [[ 32,  33,  34,  35],
        [ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]]])

In [77]:
a.shape

(3, 4, 4)

In [81]:
p = a.T
p

array([[[100,  16,  32],
        [  0,  20,  36],
        [  0,  24,  40],
        [  0,  28,  44]],

       [[  0,  17,  33],
        [  0,  21,  37],
        [  0,  25,  41],
        [  0,  29,  45]],

       [[  0,  18,  34],
        [  0,  22,  38],
        [  0,  26,  42],
        [  0,  30,  46]],

       [[  0,  19,  35],
        [  0,  23,  39],
        [  0,  27,  43],
        [  0,  31,  47]]])

In [80]:
p.shape

(4, 4, 3)

In [82]:
q = np.array([3,2,5,6,8])
q

array([3, 2, 5, 6, 8])

In [83]:
q.T

array([3, 2, 5, 6, 8])

In [84]:
np.transpose(q)

array([3, 2, 5, 6, 8])

In [86]:
v = np.array([[3,5],[6,7],[8,9]])
v

array([[3, 5],
       [6, 7],
       [8, 9]])

In [87]:
v.T

array([[3, 6, 8],
       [5, 7, 9]])

In [90]:
np.transpose(v)

array([[3, 6, 8],
       [5, 7, 9]])

In [91]:
v


array([[3, 5],
       [6, 7],
       [8, 9]])

# SCALAR MATHS

In [93]:
v+100

array([[103, 105],
       [106, 107],
       [108, 109]])

In [94]:
v-100

array([[-97, -95],
       [-94, -93],
       [-92, -91]])

In [95]:
v*2

array([[ 6, 10],
       [12, 14],
       [16, 18]])

In [96]:
v/2


array([[1.5, 2.5],
       [3. , 3.5],
       [4. , 4.5]])

In [97]:
v**2

array([[ 9, 25],
       [36, 49],
       [64, 81]], dtype=int32)

In [98]:
v//2

array([[1, 2],
       [3, 3],
       [4, 4]], dtype=int32)

In [99]:
v%2

array([[1, 1],
       [0, 1],
       [0, 1]], dtype=int32)

In [100]:
np.add(v,100)

array([[103, 105],
       [106, 107],
       [108, 109]])

In [101]:
np.subtract(v,2)

array([[1, 3],
       [4, 5],
       [6, 7]])

In [102]:
np.multiply(v,6)

array([[18, 30],
       [36, 42],
       [48, 54]])

In [106]:
np.divide(v,2)

array([[1.5, 2.5],
       [3. , 3.5],
       [4. , 4.5]])

# VECTOR MATHS

In [107]:
a

array([[[100,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]],

       [[ 32,  33,  34,  35],
        [ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]]])

In [108]:
b

array([100,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47])

In [109]:
c

array([200,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47])

In [111]:
x

array([100,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47])

In [112]:
y

array([[100,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
         37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47]])

In [113]:
p

array([[[100,  16,  32],
        [  0,  20,  36],
        [  0,  24,  40],
        [  0,  28,  44]],

       [[  0,  17,  33],
        [  0,  21,  37],
        [  0,  25,  41],
        [  0,  29,  45]],

       [[  0,  18,  34],
        [  0,  22,  38],
        [  0,  26,  42],
        [  0,  30,  46]],

       [[  0,  19,  35],
        [  0,  23,  39],
        [  0,  27,  43],
        [  0,  31,  47]]])

In [114]:
a

array([[[100,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]],

       [[ 32,  33,  34,  35],
        [ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]]])

In [116]:
a.resize(4,4,3)

In [117]:
a

array([[[100,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23]],

       [[ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35]],

       [[ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44],
        [ 45,  46,  47]]])

In [118]:
a+p

array([[[200,  16,  32],
        [  0,  20,  36],
        [  0,  24,  40],
        [  0,  28,  44]],

       [[  0,  17,  33],
        [  0,  37,  54],
        [ 18,  44,  61],
        [ 21,  51,  68]],

       [[ 24,  43,  60],
        [ 27,  50,  67],
        [ 30,  57,  74],
        [ 33,  64,  81]],

       [[ 36,  56,  73],
        [ 39,  63,  80],
        [ 42,  70,  87],
        [ 45,  77,  94]]])

In [119]:
a-p

array([[[  0, -16, -32],
        [  0, -20, -36],
        [  0, -24, -40],
        [  0, -28, -44]],

       [[  0, -17, -33],
        [  0,  -5, -20],
        [ 18,  -6, -21],
        [ 21,  -7, -22]],

       [[ 24,   7,  -8],
        [ 27,   6,  -9],
        [ 30,   5, -10],
        [ 33,   4, -11]],

       [[ 36,  18,   3],
        [ 39,  17,   2],
        [ 42,  16,   1],
        [ 45,  15,   0]]])

In [120]:
a*p

array([[[10000,     0,     0],
        [    0,     0,     0],
        [    0,     0,     0],
        [    0,     0,     0]],

       [[    0,     0,     0],
        [    0,   336,   629],
        [    0,   475,   820],
        [    0,   638,  1035]],

       [[    0,   450,   884],
        [    0,   616,  1102],
        [    0,   806,  1344],
        [    0,  1020,  1610]],

       [[    0,   703,  1330],
        [    0,   920,  1599],
        [    0,  1161,  1892],
        [    0,  1426,  2209]]])

In [122]:
a/p

C:\Users\Rakesh\AppData\Local\Temp\ipykernel_12760\4185472647.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/p
C:\Users\Rakesh\AppData\Local\Temp\ipykernel_12760\4185472647.py:1: RuntimeWarning: invalid value encountered in true_divide
  a/p


array([[[1.        , 0.        , 0.        ],
        [       nan, 0.        , 0.        ],
        [       nan, 0.        , 0.        ],
        [       nan, 0.        , 0.        ]],

       [[       nan, 0.        , 0.        ],
        [       nan, 0.76190476, 0.45945946],
        [       inf, 0.76      , 0.48780488],
        [       inf, 0.75862069, 0.51111111]],

       [[       inf, 1.38888889, 0.76470588],
        [       inf, 1.27272727, 0.76315789],
        [       inf, 1.19230769, 0.76190476],
        [       inf, 1.13333333, 0.76086957]],

       [[       inf, 1.94736842, 1.08571429],
        [       inf, 1.73913043, 1.05128205],
        [       inf, 1.59259259, 1.02325581],
        [       inf, 1.48387097, 1.        ]]])

In [123]:
a%p

C:\Users\Rakesh\AppData\Local\Temp\ipykernel_12760\4052815251.py:1: RuntimeWarning: divide by zero encountered in remainder
  a%p


array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0, 16, 17],
        [ 0, 19, 20],
        [ 0, 22, 23]],

       [[ 0,  7, 26],
        [ 0,  6, 29],
        [ 0,  5, 32],
        [ 0,  4, 35]],

       [[ 0, 18,  3],
        [ 0, 17,  2],
        [ 0, 16,  1],
        [ 0, 15,  0]]], dtype=int32)

In [124]:
np.add(a,p)

array([[[200,  16,  32],
        [  0,  20,  36],
        [  0,  24,  40],
        [  0,  28,  44]],

       [[  0,  17,  33],
        [  0,  37,  54],
        [ 18,  44,  61],
        [ 21,  51,  68]],

       [[ 24,  43,  60],
        [ 27,  50,  67],
        [ 30,  57,  74],
        [ 33,  64,  81]],

       [[ 36,  56,  73],
        [ 39,  63,  80],
        [ 42,  70,  87],
        [ 45,  77,  94]]])

In [125]:
a

array([[[100,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23]],

       [[ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35]],

       [[ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44],
        [ 45,  46,  47]]])

In [126]:
p

array([[[100,  16,  32],
        [  0,  20,  36],
        [  0,  24,  40],
        [  0,  28,  44]],

       [[  0,  17,  33],
        [  0,  21,  37],
        [  0,  25,  41],
        [  0,  29,  45]],

       [[  0,  18,  34],
        [  0,  22,  38],
        [  0,  26,  42],
        [  0,  30,  46]],

       [[  0,  19,  35],
        [  0,  23,  39],
        [  0,  27,  43],
        [  0,  31,  47]]])

In [127]:
np.multiply(a,p)

array([[[10000,     0,     0],
        [    0,     0,     0],
        [    0,     0,     0],
        [    0,     0,     0]],

       [[    0,     0,     0],
        [    0,   336,   629],
        [    0,   475,   820],
        [    0,   638,  1035]],

       [[    0,   450,   884],
        [    0,   616,  1102],
        [    0,   806,  1344],
        [    0,  1020,  1610]],

       [[    0,   703,  1330],
        [    0,   920,  1599],
        [    0,  1161,  1892],
        [    0,  1426,  2209]]])

In [129]:
np.power(a,p)

array([[[          0,           0,           0],
        [          1,           0,           0],
        [          1,           0,           0],
        [          1,           0,           0]],

       [[          1,           0,           0],
        [          1,           0, -1619706799],
        [          1, -1825133005,           0],
        [          1,  1610612736,  2112869559]],

       [[          1,  1530182129,           0],
        [          1,           0,   599824153],
        [          1,   961614017,           0],
        [          1,  1073741824,   715099961]],

       [[          1,  -234434403,           0],
        [          1,           0,   944053081],
        [          1,   396246515,           0],
        [          1, -2147483648,  1686099919]]], dtype=int32)

In [130]:
a//p

C:\Users\Rakesh\AppData\Local\Temp\ipykernel_12760\2692342568.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  a//p


array([[[1, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0]],

       [[0, 1, 1],
        [0, 1, 1],
        [0, 1, 1],
        [0, 1, 1]]], dtype=int32)

In [131]:
a%p

C:\Users\Rakesh\AppData\Local\Temp\ipykernel_12760\4052815251.py:1: RuntimeWarning: divide by zero encountered in remainder
  a%p


array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0, 16, 17],
        [ 0, 19, 20],
        [ 0, 22, 23]],

       [[ 0,  7, 26],
        [ 0,  6, 29],
        [ 0,  5, 32],
        [ 0,  4, 35]],

       [[ 0, 18,  3],
        [ 0, 17,  2],
        [ 0, 16,  1],
        [ 0, 15,  0]]], dtype=int32)

In [132]:
a

array([[[100,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23]],

       [[ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35]],

       [[ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44],
        [ 45,  46,  47]]])

In [133]:
a[::2]

array([[[100,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35]]])

In [134]:
a[::3]

array([[[100,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44],
        [ 45,  46,  47]]])

In [136]:
a[3]

array([[36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47]])

In [143]:
a[3,2,0]

42

In [144]:
a[3,2,0] = 4444

In [145]:
a


array([[[ 100,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[   0,    0,    0],
        [   0,   16,   17],
        [  18,   19,   20],
        [  21,   22,   23]],

       [[  24,   25,   26],
        [  27,   28,   29],
        [  30,   31,   32],
        [  33,   34,   35]],

       [[  36,   37,   38],
        [  39,   40,   41],
        [4444,   43,   44],
        [  45,   46,   47]]])

In [147]:
a[2:]

array([[[  24,   25,   26],
        [  27,   28,   29],
        [  30,   31,   32],
        [  33,   34,   35]],

       [[  36,   37,   38],
        [  39,   40,   41],
        [4444,   43,   44],
        [  45,   46,   47]]])

In [148]:
a[:2:2]

array([[[100,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]])

In [149]:
a[3][1] = 6

In [150]:
a

array([[[ 100,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[   0,    0,    0],
        [   0,   16,   17],
        [  18,   19,   20],
        [  21,   22,   23]],

       [[  24,   25,   26],
        [  27,   28,   29],
        [  30,   31,   32],
        [  33,   34,   35]],

       [[  36,   37,   38],
        [   6,    6,    6],
        [4444,   43,   44],
        [  45,   46,   47]]])

In [151]:
a[::-1]

array([[[  36,   37,   38],
        [   6,    6,    6],
        [4444,   43,   44],
        [  45,   46,   47]],

       [[  24,   25,   26],
        [  27,   28,   29],
        [  30,   31,   32],
        [  33,   34,   35]],

       [[   0,    0,    0],
        [   0,   16,   17],
        [  18,   19,   20],
        [  21,   22,   23]],

       [[ 100,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]]])

In [152]:
a

array([[[ 100,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[   0,    0,    0],
        [   0,   16,   17],
        [  18,   19,   20],
        [  21,   22,   23]],

       [[  24,   25,   26],
        [  27,   28,   29],
        [  30,   31,   32],
        [  33,   34,   35]],

       [[  36,   37,   38],
        [   6,    6,    6],
        [4444,   43,   44],
        [  45,   46,   47]]])

In [153]:
a[2:4]

array([[[  24,   25,   26],
        [  27,   28,   29],
        [  30,   31,   32],
        [  33,   34,   35]],

       [[  36,   37,   38],
        [   6,    6,    6],
        [4444,   43,   44],
        [  45,   46,   47]]])

In [155]:
a[2:3] = 2

In [156]:
a


array([[[ 100,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[   0,    0,    0],
        [   0,   16,   17],
        [  18,   19,   20],
        [  21,   22,   23]],

       [[   2,    2,    2],
        [   2,    2,    2],
        [   2,    2,    2],
        [   2,    2,    2]],

       [[  36,   37,   38],
        [   6,    6,    6],
        [4444,   43,   44],
        [  45,   46,   47]]])