In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [4]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
b =a.reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
np.append(a,222)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23, 222])

In [15]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
np.append(a,[122,145,136,256])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23, 122, 145,
       136, 256])

In [22]:
np.append(b,[[3,4,6,5]],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 3,  4,  6,  5]])

In [24]:
np.append(b,[[67,68,69,66]],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [67, 68, 69, 66]])

In [25]:
np.append(b,[[3],[9],[8],[99],[77],[98]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  3,  9,  8, 99, 77, 98])

In [26]:
np.append(b,[[6],[7],[9],[99],[35],[88]],axis=1)

array([[ 0,  1,  2,  3,  6],
       [ 4,  5,  6,  7,  7],
       [ 8,  9, 10, 11,  9],
       [12, 13, 14, 15, 99],
       [16, 17, 18, 19, 35],
       [20, 21, 22, 23, 88]])

In [32]:
np.delete(a,2)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [34]:
np.delete(a,2)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [35]:
np.delete(a,38)

IndexError: index 38 is out of bounds for axis 0 with size 24

In [36]:
np.delete(a,23)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [37]:
np.delete(22,a)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [40]:
c = np.append(a,[6,8,8,9,89])

In [42]:
x = set(c)
x

{0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 89}

In [45]:
x=np.array(x)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 89])

In [46]:
np.delete(b,-1,axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
np.delete(b,-1,axis=1)

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18],
       [20, 21, 22]])

# np.CONCATENATE

In [50]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [51]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 89])

In [56]:
ax = np.array(set(np.concatenate((a,x))))
ax

array({0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 89},
      dtype=object)

In [57]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
c=np.array([[44,33,55,66]])
c

array([[44, 33, 55, 66]])

In [66]:
np.concatenate((b,c))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [44, 33, 55, 66]])

In [68]:
p = np.arange(20)
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
p.resize(4,5)

In [70]:
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [72]:
q = np.array([[33,44,55,66,77]])
q

array([[33, 44, 55, 66, 77]])

In [80]:
np.concatenate((p,q),axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [33, 44, 55, 66, 77]])

In [74]:
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [77]:
t = np.array([[23],[34],[45],[56]])
t

array([[23],
       [34],
       [45],
       [56]])

In [79]:
np.concatenate((p,t),axis=1)

array([[ 0,  1,  2,  3,  4, 23],
       [ 5,  6,  7,  8,  9, 34],
       [10, 11, 12, 13, 14, 45],
       [15, 16, 17, 18, 19, 56]])

# NP.INSERT

In [81]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [82]:
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
np.insert(p,3,230)

array([  0,   1,   2, 230,   3,   4,   5,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19])

In [86]:
np.insert(p,6,-56)


array([  0,   1,   2,   3,   4,   5, -56,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19])

In [87]:
np.insert(p,-5,8990)

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14, 8990,   15,   16,   17,   18,   19])

In [90]:
np.insert(p,20,666)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 666])

In [91]:
np.insert(p,25,77)

IndexError: index 25 is out of bounds for axis 0 with size 20

In [92]:
np.insert(p,21,4444)

IndexError: index 21 is out of bounds for axis 0 with size 20

In [98]:
np.insert(p,3,[[3,4,5,333,34.5]],axis=0)

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [  3,   4,   5, 333,  34],
       [ 15,  16,  17,  18,  19]])

In [110]:

s = np.insert(p,3,[[3,4,5,9]],axis=1)

In [111]:
s

array([[ 0,  1,  2,  3,  3,  4],
       [ 5,  6,  7,  4,  8,  9],
       [10, 11, 12,  5, 13, 14],
       [15, 16, 17,  9, 18, 19]])

# NP.SPLIT

In [113]:
s.resize(6,4)
s

array([[ 0,  1,  2,  3],
       [ 3,  4,  5,  6],
       [ 7,  4,  8,  9],
       [10, 11, 12,  5],
       [13, 14, 15, 16],
       [17,  9, 18, 19]])

In [123]:
np.split(s,6,axis=0)

[array([[0, 1, 2, 3]]),
 array([[3, 4, 5, 6]]),
 array([[7, 4, 8, 9]]),
 array([[10, 11, 12,  5]]),
 array([[13, 14, 15, 16]]),
 array([[17,  9, 18, 19]])]

In [124]:
np.split(s,4,axis=1)

[array([[ 0],
        [ 3],
        [ 7],
        [10],
        [13],
        [17]]),
 array([[ 1],
        [ 4],
        [ 4],
        [11],
        [14],
        [ 9]]),
 array([[ 2],
        [ 5],
        [ 8],
        [12],
        [15],
        [18]]),
 array([[ 3],
        [ 6],
        [ 9],
        [ 5],
        [16],
        [19]])]

In [129]:
s =np.vsplit(s,2)
s

AttributeError: 'list' object has no attribute 'shape'

In [131]:
x,y=s

In [132]:
x

array([[0, 1, 2, 3],
       [3, 4, 5, 6],
       [7, 4, 8, 9]])

In [133]:
np.split(x,2,axis=1)


[array([[0, 1],
        [3, 4],
        [7, 4]]),
 array([[2, 3],
        [5, 6],
        [8, 9]])]

In [136]:
np.split(x,3,axis=0)

[array([[0, 1, 2, 3]]), array([[3, 4, 5, 6]]), array([[7, 4, 8, 9]])]

In [141]:
np.hsplit(y,2)

[array([[10, 11],
        [13, 14],
        [17,  9]]),
 array([[12,  5],
        [15, 16],
        [18, 19]])]

In [146]:
np.vsplit(x,3)

[array([[0, 1, 2, 3]]), array([[3, 4, 5, 6]]), array([[7, 4, 8, 9]])]

# NP.WHERE

In [147]:
x


array([[0, 1, 2, 3],
       [3, 4, 5, 6],
       [7, 4, 8, 9]])

In [149]:
np.where(x<=2,'True','False')

array([['True', 'True', 'True', 'False'],
       ['False', 'False', 'False', 'False'],
       ['False', 'False', 'False', 'False']], dtype='<U5')

In [151]:
c=np.arange(80)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [154]:
np.where(c%2==0,c,'false')

array(['0', 'false', '2', 'false', '4', 'false', '6', 'false', '8',
       'false', '10', 'false', '12', 'false', '14', 'false', '16',
       'false', '18', 'false', '20', 'false', '22', 'false', '24',
       'false', '26', 'false', '28', 'false', '30', 'false', '32',
       'false', '34', 'false', '36', 'false', '38', 'false', '40',
       'false', '42', 'false', '44', 'false', '46', 'false', '48',
       'false', '50', 'false', '52', 'false', '54', 'false', '56',
       'false', '58', 'false', '60', 'false', '62', 'false', '64',
       'false', '66', 'false', '68', 'false', '70', 'false', '72',
       'false', '74', 'false', '76', 'false', '78', 'false'], dtype='<U11')

In [155]:

np.where(c%5==0,c,0)

array([ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0, 10,  0,  0,  0,  0, 15,  0,
        0,  0,  0, 20,  0,  0,  0,  0, 25,  0,  0,  0,  0, 30,  0,  0,  0,
        0, 35,  0,  0,  0,  0, 40,  0,  0,  0,  0, 45,  0,  0,  0,  0, 50,
        0,  0,  0,  0, 55,  0,  0,  0,  0, 60,  0,  0,  0,  0, 65,  0,  0,
        0,  0, 70,  0,  0,  0,  0, 75,  0,  0,  0,  0])

In [157]:
list(c,end='')

TypeError: list() takes no keyword arguments

In [159]:
ls=[]

[6, 7, 8, 99]

In [160]:
ls.append(25)

In [161]:
ls

[6, 7, 8, 99, 25]