# Inspecting properties of Numpy

In [8]:
import numpy as np

y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x = np.array([[12,23,25],[14,5,8],[56,87,98]])
x

array([[12, 23, 25],
       [14,  5,  8],
       [56, 87, 98]])

In [6]:
x.size

9

In [7]:
x.shape

(3, 3)

In [9]:
y.size

10

In [12]:
y.shape

(10,)

In [10]:
len(x)

3

In [11]:
len(y)

10

# ##Data type

In [13]:
x.dtype

dtype('int32')

In [14]:
y.dtype

dtype('int32')

In [15]:
x= np.array([1,2,3,4,5,6,56.2,56.5])

In [16]:
x.dtype

dtype('float64')

In [18]:
y = np.array([2+3j,5+3j])

In [19]:
y.dtype

dtype('complex128')

In [21]:
np.array([1,1,3],dtype=complex)


array([1.+0.j, 1.+0.j, 3.+0.j])

In [22]:
w = np.array([2,4,6,8,69,4,6,78,9])

In [23]:
w

array([ 2,  4,  6,  8, 69,  4,  6, 78,  9])

In [24]:
w.astype

<function ndarray.astype>

In [29]:
w.astype(float)

array([ 2.,  4.,  6.,  8., 69.,  4.,  6., 78.,  9.])

In [30]:
w

array([ 2,  4,  6,  8, 69,  4,  6, 78,  9])

In [27]:
w.astype(int)

array([ 2,  4,  6,  8, 69,  4,  6, 78,  9])

In [28]:
w


array([ 2,  4,  6,  8, 69,  4,  6, 78,  9])

In [31]:
w.astype(complex)

array([ 2.+0.j,  4.+0.j,  6.+0.j,  8.+0.j, 69.+0.j,  4.+0.j,  6.+0.j,
       78.+0.j,  9.+0.j])

In [32]:
w

array([ 2,  4,  6,  8, 69,  4,  6, 78,  9])

In [40]:
w.astype('float8')

TypeError: data type 'float8' not understood

In [42]:
w.astype('float64')

array([ 2.,  4.,  6.,  8., 69.,  4.,  6., 78.,  9.])

In [17]:
import numpy as np
print(dir('w'))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [44]:
w.astype('f8')

array([ 2.,  4.,  6.,  8., 69.,  4.,  6., 78.,  9.])

In [46]:
w.astype('complex128')

array([ 2.+0.j,  4.+0.j,  6.+0.j,  8.+0.j, 69.+0.j,  4.+0.j,  6.+0.j,
       78.+0.j,  9.+0.j])

In [48]:
w.astype('complex64')

array([ 2.+0.j,  4.+0.j,  6.+0.j,  8.+0.j, 69.+0.j,  4.+0.j,  6.+0.j,
       78.+0.j,  9.+0.j], dtype=complex64)

In [49]:
w.astype('complex256')

TypeError: data type 'complex256' not understood

In [52]:
w

array([ 2,  4,  6,  8, 69,  4,  6, 78,  9])

In [5]:
import numpy as np
f = np.array([[5,76,3],[4,5,7],[3,77,9]])
f

array([[ 5, 76,  3],
       [ 4,  5,  7],
       [ 3, 77,  9]])

In [6]:
type(f)

numpy.ndarray

In [8]:
f.tolist()

[[5, 76, 3], [4, 5, 7], [3, 77, 9]]

In [10]:
f.tostring()

C:\Users\Rakesh\AppData\Local\Temp\ipykernel_7056\1561921577.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  f.tostring()


b'\x05\x00\x00\x00L\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x07\x00\x00\x00\x03\x00\x00\x00M\x00\x00\x00\t\x00\x00\x00'

In [11]:
f.tobytes()

b'\x05\x00\x00\x00L\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x07\x00\x00\x00\x03\x00\x00\x00M\x00\x00\x00\t\x00\x00\x00'

In [12]:
list(f)

[array([ 5, 76,  3]), array([4, 5, 7]), array([ 3, 77,  9])]

In [22]:
print(dir(np.array))

['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__self__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__text_signature__']


In [23]:
print(dir(f))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [24]:
dict(f)

ValueError: dictionary update sequence element #0 has length 3; 2 is required

In [25]:
g = np.array([[7,8],[9,5],[89,87]])

In [26]:
dict(g)

{7: 8, 9: 5, 89: 87}

In [45]:
d = np.array([[4,[7,4]],[6,[9,8]]])

C:\Users\Rakesh\AppData\Local\Temp\ipykernel_7056\1534259141.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d = np.array([[4,[7,4]],[6,[9,8]]])


In [39]:
dict(d)

{4: [7, 4], 6: [9, 8]}

In [40]:
type(d)

numpy.ndarray

In [41]:
d.ndim

2

In [46]:
d

array([[4, list([7, 4])],
       [6, list([9, 8])]], dtype=object)

In [50]:
a= np.array([[4,(7,4)],[6,(9,8)]],dtype='object')   #COMPARE CELL NO.  45 AND 50

In [48]:
a

array([[4, (7, 4)],
       [6, (9, 8)]], dtype=object)

In [57]:
q=np.array([[[2,3],[4,5]],[[5,9],[34,9]]])

In [58]:
q

array([[[ 2,  3],
        [ 4,  5]],

       [[ 5,  9],
        [34,  9]]])

In [59]:
dict(q)

TypeError: unhashable type: 'numpy.ndarray'

In [62]:
q=np.array([[[2,3],[4,5]]])

In [63]:
dict(q)

TypeError: unhashable type: 'numpy.ndarray'

In [3]:
import numpy as np

g = np.array([[[2,3],[4,5]],[[1,5],[4,9]],[[3,8],[6,7]]])
g

array([[[2, 3],
        [4, 5]],

       [[1, 5],
        [4, 9]],

       [[3, 8],
        [6, 7]]])

In [4]:
g.sum()

57

In [5]:
np.sum(g)

57

In [6]:
np.sum(g,axis=1)

array([[ 6,  8],
       [ 5, 14],
       [ 9, 15]])

In [7]:
np.sum(g,axis=0)

array([[ 6, 16],
       [14, 21]])

In [9]:
a = np.array([[6,8],[8,9],[99,55]])

In [10]:
a

array([[ 6,  8],
       [ 8,  9],
       [99, 55]])

In [11]:
np.sum(a,axis=0)

array([113,  72])

In [16]:
np.subtract(g[0],g[1])

array([[ 1, -2],
       [ 0, -4]])

In [17]:
g

array([[[2, 3],
        [4, 5]],

       [[1, 5],
        [4, 9]],

       [[3, 8],
        [6, 7]]])

In [21]:
np.subtract(g[2],g[1])

array([[ 2,  3],
       [ 2, -2]])

In [23]:
np.multiply(g[1],g[2])

array([[ 3, 40],
       [24, 63]])

In [24]:
np.divide(g[1],g[0])

array([[0.5       , 1.66666667],
       [1.        , 1.8       ]])

In [28]:
np.power(g[0],g[1],dtype='int16')

array([[     2,    243],
       [   256, -12955]], dtype=int16)

In [31]:
np.mod(g[0],g[1])

array([[0, 3],
       [0, 5]], dtype=int32)

In [32]:
np.mean(g)

4.75

In [33]:
np.min(g)

1

In [35]:
np.max(g)

9

In [37]:
np.median(g)

4.5